### ISSUE TITLE
Doesn't work in 0.5.3

### ISSUE THREAD

**Issue by ghost** [syl3r86/Actually-Private-Rolls#1]
Hey, just got directed to your mod for private rolls and turns out it's now defunct :(
Just letting you know incase you don't :)

**Comment by syl3r86** [comment]
it works fine for me personally. message me in discord please with what's not working for you. it's easier to talk there

**Comment by ghost** [comment]
Ah, sorry. There were like 3-4 things I wasn't doing right so every time I thought I'd found the fix it didn't work :D

It's working. 
List of all the things I did wrong: 
- Module wasn't enables -_-
- Wasn't rolling privately... That one I figured out quickly enough :p
- You know that drop down above the input box? It was set to private but the rolls were not private. That confused the crap out of me. I assumed it made anything I typed private or blind or self. Turns out it just sets the default for sheet rolls or something.
- Forgot to update this when I realised I was being a numpty when my rolls were mysteriously not appearing on my fake player window :p

Edit: Can't believe the system doesn't do this by default :D
